@_3._2_Background_Service_vs_IHostedService_in_API_HostAddress = http://localhost:5175

GET {{_3._2_Background_Service_vs_IHostedService_in_API_HostAddress}}/weatherforecast/
Accept: application/json

###
